#!/bin/sh
. /usr/share/os-prober/common.sh

set -e

newns "$@"
require_tmpdir

grep "^/dev/" /proc/mounts | parse_proc_mounts >"$OS_PROBER_TMP/mounted-map" || true

partition="$1"
subvolid="$2"

if [ -z "$partition" ]; then
	echo "usage: linux-boot-prober partition" >&2
	exit 1
fi

if ! mapped="$(mapdevfs "$partition")"; then
	log "Device '$partition' does not exist; skipping"
	continue
fi

if ! mrecord="$(grep "^$mapped [^ ]* [^ ]* $subvolid" "$OS_PROBER_TMP/mounted-map")"; then
	for test in /usr/lib/linux-boot-probes/*; do
		debug "running $test"
		if [ -x $test ] && [ -f $test ]; then
			if $test "$partition" "$subvolid"; then
				debug "linux detected by $test"
				break
			fi
		fi
	done
else
	mpoint=$(echo "$mrecord" | head -n1 | cut -d " " -f 2)
	mpoint="$(unescape_mount "$mpoint")"
	if [ "$mpoint" != "/target/boot" ] && [ "$mpoint" != "/target" ] && [ "$mpoint" != "/" ]; then
		type=$(echo "$mrecord" | head -n1 | cut -d " " -f 3)
		linux_mount_boot "$partition" "$mpoint" "$subvolid"
		set -- $mountboot
		bootpart="$1"
		bootmounted="$2"
		bootsubvolid="$3"
		for test in /usr/lib/linux-boot-probes/mounted/*; do
			if [ -f $test ] && [ -x $test ]; then
				debug "running $test on mounted $partition"
				if $test "$partition" "$bootpart" "$mpoint" "$type" "$subvolid" "$bootsubvolid"; then
					debug "$test succeeded"
					break
				fi
			fi
		done
		if [ "$bootmounted" = 1 ]; then
			if ! umount "$mpoint/boot"; then
				warn "failed to umount $mpoint/boot"
			fi
		fi
	fi
fi
