#!/bin/sh -e
# Detects Mac OS X. I don't yet know how Mac OS <= 9 fits into this.
. /usr/share/os-prober/common.sh

partition="$1"
mpoint="$2"
type="$3"

debug() {
  if [ -z "$OS_PROBER_DISABLE_DEBUG" ]; then
    logger -t macosx-prober "debug: $@"
  fi
}

# Weed out stuff that doesn't apply to us
case "$type" in
  hfsplus) debug "$1 is an HFS+ partition" ;;
  *) debug "$1 is not an HFS+ partition: exiting"; exit 1 ;;
esac

# Could use a better test than this.
# /System/Library/CoreServices/SystemVersion.plist has version information,
# but I don't think it exists on Mac OS <= 9, and it's XML so parsing in
# shell will be nasty.

if [ -r "$2/System/Library/CoreServices/SystemVersion.plist" ]; then
  label="$(count_next_label MacOSX)"
  plist="$(plist2strings "$2/System/Library/CoreServices/SystemVersion.plist")"
  build="$(echo "$plist" | cut -f1)"
  name="$(echo "$plist" | cut -f2)"
  version="$(echo "$plist" | cut -f3)"
  [ -e "$2/mach_kernel" ] && : ${name:=Mac OS X}
  [ "$name" ] || exit 1
  if [ "$version" ]; then
    description="$name ($version${build:+"!$build"})"
  else
    description="$name${build:+" $build"}"
  fi
  result "$1:$description:$label:macosx"
  exit 0
elif [ -e "$2/mach_kernel" ]; then
  label="$(count_next_label MacOSX)"
  result "$1:Mac OS X:$label:macosx"
  exit 0
else
  exit 1
fi
